### ISSUE TITLE
Failed to init user authentication. Please contact a system administrator

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#142]
I have deployed the platform, which successfully works via localhost.
When I try to access GUI via ip-address I receive the exception.

May be because it fails to load keycloak-config from localhost:8080 , but where I don't know where I c modify it
See console trace https://gyazo.com/10337fbe1ae9d62802359c68e95f32ca

**Comment by MichaelRoeder** [comment]
Sorry, but I am partly confused regarding your setup. From #140 it looked like you want to access the platfrom via `http://localhost:8082`. But now, you are using an IP.

Which OS are you using? Which address should the platform have and which address should Keycloak have?

**Comment by smirnp** [comment]
I did different attempts with configurations during setup. Finally it works on the default values (8080):
```
gui:
    build: ./hobbit-gui/gui-serverbackend
    ports:
      - "8080:8080"
    networks:
      - hobbit-core
      - hobbit
    depends_on:
      - platform-controller
      - rabbit
      - virtuoso
    environment:
      - HOBBIT_RABBIT_HOST=rabbit
      - KEYCLOAK_AUTH_URL=http://keycloak:8181/auth
      - CHECK_REALM_URL=false
      - KEYCLOAK_DIRECT_URL=http://keycloak:8080/auth

  # Keycloak user management (used by the GUI)
  keycloak:
    image: git.project-hobbit.eu:4567/gitadmin/hobbit-keycloak:1.0.0
    container_name: keycloak
    restart: always
    ports:
      - "8181:8080"
    networks:
      - hobbit
    volumes:
      - ./config/keycloak:/opt/jboss/keycloak/standalone/data/db
```
But it works only via localhost:8080. Attempts for access it via 192.168.56.20 fail with the provided exception, while Keycloak interface is available via http://192.168.56.20:8181. [Here](https://gyazo.com/42ca20efac7ca9776193ff37736b934e) is its configuration
