### ISSUE TITLE
Keycloak redirect problem in 1.0.14

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#188]
After calling 192.168.56.20:8080 I'm always redirecting to localhost:8181/...   (which is not found, if I have platform somewhere except localhost)

Here is my keycloak configuration:
https://i.gyazo.com/42ca20efac7ca9776193ff37736b934e.png  

This configuration works fine for 1.0.12, but does not work for 1.0.14. 

So I can use 1.0.14 only via localhost:8080

**Comment by MichaelRoeder** [comment]
The redirect URL is set via the docker-compose file (https://github.com/hobbit-project/platform/blob/master/docker-compose.yml#L37). Please make sure that you set it to the URL that you are using to access your UI.

**Comment by smirnp** [comment]
I have the same gui section like I used for 1.0.12:

 ```
 # HOBBIT GUI
  gui:
    build: ./hobbit-gui/gui-serverbackend
    ports:
      - "8080:8080"
    networks:
      - hobbit-core
      - hobbit
#   depends_on:
#      - platform-controller
#      - rabbit
#      - virtuoso
    environment:
      - HOBBIT_RABBIT_HOST=rabbit
      - KEYCLOAK_AUTH_URL=http://192.168.56.20:8181/auth
      - CHECK_REALM_URL=false
      - KEYCLOAK_DIRECT_URL=http://keycloak:8080/auth
```
