### ISSUE TITLE
GUI shows empty screen after successful auth in 1.0.14

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#191]
I'm using the prebuilt image (approach works fine for 1.0.13):

```
  gui:
#    build: ./hobbit-gui/gui-serverbackend
    image: git.project-hobbit.eu:4567/gitadmin/platform-gui-image:1.0.14
    ports:
      - "8080:8080"
    networks:
      - hobbit-core
      - hobbit
    depends_on:
      - platform-controller
      - rabbit
      - virtuoso
    environment:
      - HOBBIT_RABBIT_HOST=rabbit
      - KEYCLOAK_AUTH_URL=http://192.168.56.20:8181/auth
      - CHECK_REALM_URL=false
      - KEYCLOAK_DIRECT_URL=http://keycloak:8080/auth
```

Here are the logs (do no change when I update the page):
```
:~/Projects/hobbit-platform_1.0.14$ sudo docker-compose up gui
hobbitplatform1014_redis_1 is up-to-date
rabbit is up-to-date
vos is up-to-date
hobbitplatform1014_storage-service_1 is up-to-date
hobbitplatform1014_platform-controller_1 is up-to-date
Starting hobbitplatform1014_gui_1 ...
Starting hobbitplatform1014_gui_1 ... done
Attaching to hobbitplatform1014_gui_1
gui_1                  | 2018-01-09 15:52:04.154:INFO::main: Logging initialized @804ms
gui_1                  | 2018-01-09 15:52:04.637:INFO:oejs.SetUIDListener:main: Setting umask=02
gui_1                  | 2018-01-09 15:52:04.674:INFO:oejs.SetUIDListener:main: Opened ServerConnector@783e6358{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
gui_1                  | 2018-01-09 15:52:04.675:INFO:oejs.SetUIDListener:main: Setting GID=999
gui_1                  | 2018-01-09 15:52:04.692:INFO:oejs.SetUIDListener:main: Setting UID=999
gui_1                  | 2018-01-09 15:52:04.706:INFO:oejs.Server:main: jetty-9.3.15.v20161220
gui_1                  | 2018-01-09 15:52:04.746:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///var/lib/jetty/webapps/] at interval 1
gui_1                  | 2018-01-09 15:52:13.701:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=7358ms
gui_1                  | 2018-01-09 15:52:14.308:WARN:oejs.SecurityHandler:main: ServletContext@o.e.j.w.WebAppContext@192b07fd{/,file:///tmp/jetty/jetty-0.0.0.0-8080-ROOT.war-_-any-6578699647905282543.dir/webapp/,STARTING}{/ROOT.war} has uncovered http methods for path: /rest/*
gui_1                  | 2018-01-09 15:52:16.601:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@192b07fd{/,file:///tmp/jetty/jetty-0.0.0.0-8080-ROOT.war-_-any-6578699647905282543.dir/webapp/,AVAILABLE}{/ROOT.war}
gui_1                  | 2018-01-09 15:52:16.641:INFO:oejs.AbstractConnector:main: Started ServerConnector@783e6358{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
gui_1                  | 2018-01-09 15:52:16.641:INFO:oejs.Server:main: Started @13292ms
gui_1                  | 2018-01-09 15:52:18,926 INFO [de.usu.research.hobbit.gui.rest.InternalResources] - <Keycloak configuration for webapp: realm=Hobbit, url=http://192.168.56.20:8181/auth, clientId=Hobbit-GUI>
```
