### ISSUE TITLE
Add log file download

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#93]
## Description

The developer of a system or a benchmark should be able to download the log files of its system after an experiment terminated.
* An experiment might need a list of system and/or benchmark containers that have been created at its runtime
* If a system / benchmark developer asks for the log files, they can be collected from Elasticsearch by using the names of the containers
    * Does only work platforms that have an ELK stack with them (i.e., it needs to be deactivated for platforms that do not support it)
    * They might be sorted based on their timestamp (Should be part of the Elasticsearch query)
* This task also includes to make the current Elasticsearch more stable. At the moment, Kibana often has a red status because Elasticsearch is not as responsive as it should be. This might lead to the situation that log files are only available for ~14 days and will be rotated to keep the Elasticsearch index small.
* The experiment result has to offer a download button for this. (Two buttons if the user is the owner of both - the benchmark and the system)
* Although the feature itself will be implemented by InfAI, it has to be decided whether querying Elasticsearch will be part of the platform controller or the GUI serverbackend.

**Comment by earthquakesan** [comment]
Working on it in [feature/logfiledownload-issue93 branch](https://github.com/hobbit-project/platform/tree/feature/logfiledownload-issue93)

**Comment by earthquakesan** [comment]
@MichaelRoeder I need help with implementing user permissions for this one. Don't completely understand the logic which is there atm.

**Comment by earthquakesan** [comment]
@Ennosigaeon the logic is ready, you might get the benchmark logs as:
```
http://localhost:8080/rest/logs/benchmark/query?id=1516045053146
```
The system logs are accessible via:
```
http://localhost:8080/rest/logs/system/query?id=1516045053146
```
id is an id of the experiment.

You will need to extend the experiment results interface with two buttons on: one for downloading benchmark logs, other is for downloading system logs (Benchmark Logs, System Logs buttons). The [ExperimentBean](https://github.com/hobbit-project/platform/blob/feature/logfiledownload-issue93/hobbit-gui/gui-serverbackend/src/main/java/de/usu/research/hobbit/gui/rest/beans/ExperimentBean.java) was extended to provide user access permissions for benchmark logs and system logs: isBenchmarkLogAvailable and isSystemLogAvailable methods.

**Comment by Ennosigaeon** [comment]
I am running into issues trying to download a log file locally.

`Caused by: java.lang.Exception: ELASTICSEARCH_HOST and ELASTICSEARCH_HTTP_PORT env are not set.`

How do I have to configure Elastic Search?

**Comment by Ennosigaeon** [comment]
I have added a button to download the log files. In theory it should work, however I wasn't able to test it with a real log file but only dummy text.

**Comment by earthquakesan** [comment]
You will need an docker-compose.override.yml as follows:
```
version: '2'
services:
  platform-controller:
    environment:
      - GITLAB_USER=gitadmin
      - GITLAB_EMAIL=gitadmin@project-hobbit.eu
      - GITLAB_TOKEN=token
      - LOGGING_GELF_ADDRESS=udp://localhost:12201

  gui:
    environment:
      - KEYCLOAK_AUTH_URL=http://localhost:8181/auth
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_HTTP_PORT=9200
```

Then you start elk stack first:
```
docker-compose -f docker-compose-elk.yml up -d
```

and then the system:
```
docker-compose build && docker-compose up
```
